package org.parttio.tetris.swing;

import org.parttio.example.tetrislib.Game;
import org.parttio.example.tetrislib.Grid;
import org.parttio.example.tetrislib.Tetromino;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

/**
 * Swing + Graphics2D version of Tetris (pretty much generated by ChatGPT based on Vaadin example).
 * <p>
 * Controls:
 * - Left/Right arrows: move piece
 * - Up arrow: rotate CW
 * - Down arrow: rotate CCW
 * - Space: drop
 * <p>
 * Fires PropertyChange events:
 * - "score" (Integer new value)
 * - "gameOver" (Boolean true)
 */
public class SwingTetris extends JFrame {

    private static final int PAUSE_TIME_MS = 500;
    private static final int PLAYFIELD_W = 10;
    private static final int PLAYFIELD_H = 20;
    private static final int TILE_SIZE = 30;
    private static final Map<String, Color> NAMED_COLORS = new HashMap<>();

    static {
        NAMED_COLORS.put("black", Color.BLACK);
        NAMED_COLORS.put("white", Color.WHITE);
        NAMED_COLORS.put("red", Color.RED);
        NAMED_COLORS.put("green", Color.GREEN);
        NAMED_COLORS.put("blue", Color.BLUE);
        NAMED_COLORS.put("yellow", Color.YELLOW);
        NAMED_COLORS.put("magenta", Color.MAGENTA);
        NAMED_COLORS.put("cyan", Color.CYAN);
        NAMED_COLORS.put("orange", Color.ORANGE);
        NAMED_COLORS.put("pink", Color.PINK);
        NAMED_COLORS.put("gray", Color.GRAY);
        NAMED_COLORS.put("lightgray", Color.LIGHT_GRAY);
        NAMED_COLORS.put("darkgray", Color.DARK_GRAY);
        // Common CSS-ish extras
        NAMED_COLORS.put("purple", new Color(128, 0, 128));
        NAMED_COLORS.put("teal", new Color(0, 128, 128));
        NAMED_COLORS.put("lime", new Color(0, 255, 0));
        NAMED_COLORS.put("navy", new Color(0, 0, 128));
        NAMED_COLORS.put("maroon", new Color(128, 0, 0));
        NAMED_COLORS.put("olive", new Color(128, 128, 0));
    }

    private final Game game;
    private final Board board;
    private Timer timer;
    private int oldScore = 0;

    public SwingTetris() {
        super("Tetris (Swing)");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        this.game = new Game(PLAYFIELD_W, PLAYFIELD_H);
        this.board = new Board();

        // Controls (mirroring your DOM buttons)
        JButton left = new JButton("⬅");
        left.addActionListener(e -> {
            game.moveLeft();
            drawGameState();
        });

        JButton right = new JButton("➡");
        right.addActionListener(e -> {
            game.moveRight();
            drawGameState();
        });

        JButton rotateCW = new JButton("↻");
        rotateCW.addActionListener(e -> {
            game.rotateCW();
            drawGameState();
        });

        JButton rotateCCW = new JButton("↺");
        rotateCCW.addActionListener(e -> {
            game.rotateCCW();
            drawGameState();
        });

        JButton drop = new JButton("⬇");
        drop.addActionListener(e -> {
            game.drop();
            drawGameState();
        });

        JPanel controls = new JPanel(new GridLayout(1, 5, 8, 0));
        controls.add(left);
        controls.add(right);
        controls.add(rotateCW);
        controls.add(rotateCCW);
        controls.add(drop);

        JPanel root = new JPanel(new BorderLayout(0, 8));
        root.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        root.add(controls, BorderLayout.NORTH);
        root.add(board, BorderLayout.CENTER);

        setContentPane(root);
        pack();
        setResizable(false);
        setLocationByPlatform(true);

        // Key bindings (works even when buttons have focus)
        installKeyBindings(board, left, right, rotateCW, rotateCCW, drop);

        // Game loop timer (EDT)
        this.timer = new Timer(PAUSE_TIME_MS, e -> {
            game.step();
            drawGameState();
            boolean over = game.isOver();
            int score = game.getScore();
            if (over) {
                timer.stop();
                // Also send to DOM if/when in browser, wrapped in try/catch not to throw if in basic
                // JVM (native method not implemented in JS)
                try {
                    fireInBrowser(score, true);
                } catch (Throwable ignored) {
                }
            } else if (score != oldScore) {
                oldScore = score;
                // Also send to DOM if/when in browser, wrapped in try/catch not to throw if in basic
                // JVM (native method not implemented in JS)
                try {
                    fireInBrowser(score, false);
                } catch (Throwable ignored) {
                }
            }
        });
        this.timer.start();
    }

    /**
     * Main entry for quick running.
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {

            SwingTetris swingTetris = new SwingTetris();
            swingTetris.setVisible(true);

            // CheerpJ, register, in try catch not to throw if run in basic JVM
            new Thread(() -> {
                try {
                    nativeSetApplication(swingTetris);
                } catch (Exception ignored) {
                }
            }).start();
        });
    }

    // ------------------------
    // Helpers
    // ------------------------

    /**
     * Map HTML/CSS-ish color names/hex used by Tetromino.get(tile).getColor() to AWT Color.
     */
    private static Color parseColor(String cssColor) {
        if (cssColor == null) return Color.WHITE;
        String s = cssColor.trim().toLowerCase();

        // Try hex (#rgb, #rrggbb)
        try {
            if (s.startsWith("#")) {
                // Support #rgb shorthand
                if (s.length() == 4) {
                    char r = s.charAt(1), g = s.charAt(2), b = s.charAt(3);
                    s = "#" + r + r + g + g + b + b;
                }
                return Color.decode(s);
            }
        } catch (NumberFormatException ignored) {
        }

        // Named colors (add more as needed)
        Map<String, Color> names = NAMED_COLORS;
        Color c = names.get(s);
        return c != null ? c : Color.WHITE;
    }

    /**
     * Install key bindings equivalent to your DOM key handlers.
     */
    private static void installKeyBindings(JComponent c,
                                           JButton left, JButton right,
                                           JButton rotateCW, JButton rotateCCW,
                                           JButton drop) {
        InputMap im = c.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = c.getActionMap();

        im.put(KeyStroke.getKeyStroke("LEFT"), "left");
        im.put(KeyStroke.getKeyStroke("RIGHT"), "right");
        im.put(KeyStroke.getKeyStroke("UP"), "rotCW");
        im.put(KeyStroke.getKeyStroke("DOWN"), "rotCCW");
        im.put(KeyStroke.getKeyStroke("SPACE"), "drop");

        am.put("left", buttonClickAction(left));
        am.put("right", buttonClickAction(right));
        am.put("rotCW", buttonClickAction(rotateCW));
        am.put("rotCCW", buttonClickAction(rotateCCW));
        am.put("drop", buttonClickAction(drop));
    }

    private static Action buttonClickAction(JButton b) {
        return new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for (ActionListener al : b.getActionListeners()) {
                    al.actionPerformed(new ActionEvent(b, ActionEvent.ACTION_PERFORMED, "keybind"));
                }
            }
        };
    }

    // CheerpJ specific, sets the "instance" available to DOM/JS
    public static native void nativeSetApplication(SwingTetris myApplication);

    public static native void fireInBrowser(int score, boolean gameOver);

    /**
     * Repaints board with the latest state.
     */
    protected synchronized void drawGameState() {
        board.repaint();
    }

    // ------------------------
    // Board: draws with Graphics2D
    // ------------------------
    private final class Board extends JPanel {

        Board() {
            setPreferredSize(new Dimension(TILE_SIZE * PLAYFIELD_W, TILE_SIZE * PLAYFIELD_H));
            setBackground(Color.DARK_GRAY);
            setFocusable(true);
            requestFocusInWindow();
        }

        @Override
        protected void paintComponent(Graphics g0) {
            super.paintComponent(g0);
            Graphics2D g = (Graphics2D) g0.create();
            try {
                g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Black playfield background (like the canvas fill)
                g.setColor(Color.BLACK);
                g.fillRect(0, 0, game.getWidth() * TILE_SIZE + 2, game.getHeight() * TILE_SIZE + 2);

                // Draw blocks
                Grid state = game.getCurrentState();
                for (int x = 0; x < state.getWidth(); x++) {
                    for (int y = 0; y < state.getHeight(); y++) {
                        int tile = state.get(x, y);
                        if (tile > 0) {
                            String colorStr = Tetromino.get(tile).getColor();
                            g.setColor(parseColor(colorStr));
                            g.fillRect(x * TILE_SIZE + 1, y * TILE_SIZE + 1, TILE_SIZE - 2, TILE_SIZE - 2);
                        }
                    }
                }
            } finally {
                g.dispose();
            }
        }
    }

}
